### PR TITLE
Resolve php 8.1 deprecations

### PR DESCRIPTION
**Pull request by natewiebe13**
Related to https://github.com/facebook/facebook-php-business-sdk/pull/554

## Checklist

- [x] I've read the [Contributing Guidelines](CONTRIBUTING.md) and the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've completed the [Contributor License Agreement](https://developers.facebook.com/opensource/cla)

## Pull Request Details

Resolves php 8.1 deprecations in a backwards compatible way.

### CODE REVIEW

**Comment by NelinD** [comment]
What's up with this request?

**Comment by Ilyasoad** [comment]
what's up guys. we are waiting this feature

**Comment by ryabininea** [comment]
We need this too. Up

**Comment by julionc** [comment]
To make the SDK feature backward compatible with older PHP versions:
- You have to use `#[\ReturnTypeWillChange]`.
- And remove `use ReturnTypeWillChange`

**Comment by natewiebe13** [comment]
Good call. Updated.

**Comment by julionc** [comment]
Ping
cc @stcheng @jingping2015

**Comment by NelinD** [comment]
Wow-wow-wow, what about the merge?

**Comment by Ilyasoad** [comment]
it's necessary for us, guys

**Comment by ryabininea** [comment]
Why was it closed? Describe the reason for closing the request, pls

**Pull request closed without merging**
